### ISSUE TITLE
Is there any (configurable) cache mechanism ?

### ISSUE THREAD

**Issue by jbar** [BBVA/kapow#107]
to possibly reduce overload an DDOS risks specially for heavy command which use to give a few changing result, which may be delayed ?

**Comment by nilp0inter** [comment]
at this moment Kapow! doesn't support any configurable middleware mechanisms like cache or throttling. But we are planning to include it in following releases.

For now we recommend using Kapow! [behind a reverse proxy](https://kapow.readthedocs.io/en/latest/examples/using_reverse_proxies.html) for any non trivial load.  Those reverse proxy already support https, cache and throttling mechanisms.

**Comment by jbar** [comment]
Thx a lot.
