### ISSUE TITLE
Securize control interface

### ISSUE THREAD

**Issue by nilp0inter** [BBVA/kapow#119]
In the current implementation the control interface is over plain HTTP and bind to localhost by default.

This can be problematic on setups where an adversary is on the same machine as the server.

Proper bastion of the control interface is key to a secure Kapow! deployment.

Think a solution and implement it.

**Comment by panchoh** [comment]
Ruso dixit:
*Kapow!* should generate a random token each time it starts up, and share this token via environment variable to the init programs it will launch upon startup.
The control interface will only accept requests that contain the aforementioned token in the header `X-Kapow-Token`.

Furthermore, to prevent sniffing of the token by other parties, the communication should be done using https, by way of generating a self-signed certificate on the fly, which can be accomplished by taking code from this example:

https://golang.org/src/crypto/tls/generate_cert.go.  We can perhaps leverage ed25519 for a lightweight and secure key.
