### ISSUE TITLE
Crashs on start on wayland

### ISSUE THREAD

**Issue by myxor** [BBVA/kapow#136]
When i start kapow on [phosh](https://developer.puri.sm/Librem5/Software_Reference/Environments/Phosh.html) which runs on wayland.
It terminates with the following error log:

```kapow server --bind 0.0.0.0:8080 pows/powfile.pow
No protocol specified
qt.qpa.xcb: could not connect to display :0.0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.
```

I am not sure how to get this running.

**Comment by nilp0inter** [comment]
Which kapow binary are you using?

**Comment by myxor** [comment]
Sorry i was trying https://aur.archlinux.org/packages/kapow/ but that package is not this kapow.
I will close this ticket :)
