### ISSUE TITLE
kapow use bash or shell?

### ISSUE THREAD

**Issue by vay3t** [BBVA/kapow#139]
I'm making a regrettable attempt to do a backend with bash and I had that doubt

![image](https://user-images.githubusercontent.com/6080369/99890627-2548f700-2c40-11eb-9167-f7b1c03f04d0.png)

**Comment by nilp0inter** [comment]
To this day *Kapow!* uses the default entrypoint `/bin/sh -c`. You can change it passing the parameter `-e` to `kapow route add`.

In your case:

```
kapow route add / -e '/bin/bash -c' - <<-'EOF'
....
EOF
```

This situation will change when #95 gets implemented.
