### ISSUE TITLE
[Feature request] Add chroot option

### ISSUE THREAD

**Issue by earizon** [BBVA/kapow#150]
Some "alternatives" like socat has some nice security options that would be great to replicate in kapow, like execution of the script in a "chrooted" enviroment.

As a reference, extracted from: https://fossies.org/linux/socat/EXAMPLES

```
  256 // make a program available on the network chrooted, unprivileged; 
  257 // parent process stays in / running as root
  258 // script path is already chrooted
  259 # socat -lm -d -d TCP-LISTEN:5555,fork EXEC:/bin/myscript,chroot=/home/sandbox,su=sandbox,pty,stderr
```

**Comment by panchoh** [comment]
Hi, @earizon.

First, let me say that we **don't recommend** running *Kapow!* as `root`.

Implementing a built-in chroot feature would require to run `kapow` as root
permanently.  Or perhaps this feature could be implemented more securely, but
it would most likely complicate the server further.

Furthermore, this feature would not be portable to Windows®.

Not everything is lost, though.  Note that you can trivially obtain what
you want making use of `sudo` and `chroot`:

``` sh
# Note that `kapow` must be available under $PATH relative to /some/path
kapow route add /chrooted				\
	-e 'sudo --preserve-env=KAPOW_HANDLER_ID,KAPOW_DATA_URL chroot --userspec=sandbox /some/path /bin/sh -c'		\
	-c 'ls / | kapow set /response/body'
```

We'll close this issue now.  Feel free to comment if you feel that something
else is needed.
