### ISSUE TITLE
Unexpected dummy return

### ISSUE THREAD

**Issue by panchoh** [BBVA/kapow#34]
As per the spec, this call should return the actual route inserted, with the final values for all its fields.

https://github.com/BBVA/kapow/blob/f5d7521a454e58ae90e62cf8786b0fdd47dd26bc/internal/server/user/state.go#L33

Co-authored-by: César Gallego <gallego.cesar@gmail.com>

**Comment by nilp0inter** [comment]
I am not sure about who should fill up the ID field.

**Comment by hhurtado** [comment]
Isn't this already solved?

**Comment by panchoh** [comment]
> Isn't this already solved?

Yes. It was fixed by 304276db47fbf4.

See:
https://github.com/BBVA/kapow/blob/d9e072f89a425093ca25ae65494fb7b78f7554d3/internal/server/user/state.go#L40

Also, it is a duplicate of #42.
