### ISSUE TITLE
Implement missing reason phrase in control and data API

### ISSUE THREAD

**Issue by nilp0inter** [BBVA/kapow#37]

**Comment by panchoh** [comment]
I posit that we should perhaps not do this, in the light of this:
https://evertpot.com/http-2-finalized/  (look for 'reason phrase')
TL;DR: HTTP/2 does away with the reason phrase.

**Comment by panchoh** [comment]
Let's postpone this until we have a chance to discuss it.

**Comment by nilp0inter** [comment]
The custom reason phrases in the spec contains an important part of the message given to the client (the human explanation), so this can't be removed.
Given that is not likely that we use HTTP/2+ in the control/data API anyway, we decided **to maintain the information in the reason phrase**; if we finally decide to move to HTTP/2+ the messages will be moved to **a custom header** (not to the body because it adds complexity to the rest of the system).

**Comment by nilp0inter** [comment]
Reason phrases where substituted by JSON payloads.
