### ISSUE TITLE
cmd/route: read command from parameter, file or stdin

### ISSUE THREAD

**Issue by panchoh** [BBVA/kapow#46]
https://github.com/BBVA/kapow/blob/be6a2efcc49d9e33cd215f79c04531ceb89b6d32/internal/cmd/route.go#L43

**Comment by panchoh** [comment]
Recap:
1. -c + string
2. file.pow
3. -
4. null command

**Comment by CesarGallego** [comment]
The file to read must be a entry point "compilant" file, not a pow file. Right?

**Comment by panchoh** [comment]
> The file to read must be a entry point "compilant" file, not a pow file. Right?

Yes, AFAIK
