### ISSUE TITLE
`kapow server powfile.pow` should exec `powfile.pow` if possible

### ISSUE THREAD

**Issue by panchoh** [BBVA/kapow#62]
As a `Kapow!` user, I would like to control the scripting I use to configure the `kapow` server.

Right now, the `powfile.pow` is always treated as a `bash` script.

But, if I wanted to use a different method to call `kapow route...`, say from a `dash` script, Perl script, Python script, or `bash` script but selected via `#!/usr/bin/env` mechanism, I couldn't do it cleanly as it is now.

I propose to implement a teeny tiny bit of logic to examine the executable bit of the `powfile.pow`, and try to `exec` it instead of passing it to `bash`.

https://github.com/BBVA/kapow/blob/f4b9a96a0648465a076c4b1af3b461a22dff6ec6/internal/cmd/server.go#L55

**Comment by hhurtado** [comment]
Closed, contiue in #95
