### ISSUE TITLE
New nmap example is not async

### ISSUE THREAD

**Issue by nilp0inter** [BBVA/kapow#65]
I am having a hard time understanding the intended behavior of the new nmap examples, in particular the callback one.

With the current implementation the route will block until the nmap scan finish and the callback is called and returned. It's that the intended behavior? If it is, what's the improvement over returning the nmap scan in the response?

**Comment by panchoh** [comment]
I'm not sure I understand it either. @cr0hn, will you enlighten us?

**Comment by panchoh** [comment]
I've had a session with @cr0hn, where he clarified his intentions. I'll summarize them later.

**Comment by panchoh** [comment]
> I've had a session with @cr0hn, where he clarified his intentions. I'll summarize them later.

@cr0hn reckons that an `Nmap` run can take a long long time¹, hours even, when scanning large networks.

Usually, `Nmap` produces output on its `stdout` upon completion of the scan.  But if `Nmap` is fed the `-v` argument (once or more), or if  SCRIPT SCAN is performed, then `Nmap` provides feedback as the scan progresses.

Well, @cr0hn's intention is to *stream* this running feedback to the consumer of the `Nmap` `Kapow!` service, to keep them informed of the progress of the long-running `Nmap` run, and finally provide them with the `XML` report.

The end of the feedback is separated from the actual `XML` report by a marker, namely `########`.  Not ideal, but I think that we can't handle yet serving multiple files.

The `callback` flavour would then stream the `Nmap` feedback through the current response's body, and when the report is ready, push it somewhere else with a handy `curl`.

@cr0hn, did I capture it correctly?

Thanks for watching.

¹: https://www.youtube.com/watch?v=6-1Ue0FFrHY

**Comment by nilp0inter** [comment]
I understand the use case now. But having an HTTP connection open for such a long time is usually not a good idea (think of timeouts in proxies for example).

A better approach I think is to return a job identifier and write the nmap log to disk with the same identifier as the filename.

When the user wants to see the status they just ask another url that  `tail -F` the log file.

This way we can detach nmap inmediatelly, additionally more than one user can inspect the log at the same time. 

I think the use case is very good, but needs more work. 

Can we revert it and delay this until 1.1.0?

**Comment by panchoh** [comment]
> Can we revert it and delay this until 1.1.0?
I concur.

**Comment by panchoh** [comment]
@cr0hn, I've put the examples on a branch, https://github.com/BBVA/kapow/tree/nmap-examples, so that we can keep working on them until they are ready to be merged.
