### ISSUE TITLE
kapow set /request/headers/Content-Type text/xml produces bad header

### ISSUE THREAD

**Issue by panchoh** [BBVA/kapow#67]
Steps to reproduce:
1. Create `buggy-set-headers.pow`:
```bash
cat > buggy-set-headers.pow <<'EOPOW'
kapow route add / - <<-'EOF'
	kapow set /response/headers/Content-Type text/xml
EOF
EOPOW
```
2. Run `kapow server` on it:
```bash
kapow server buggy-set-headers.pow
```
3. Query with `curl`:
```bash
curl -v http://localhost:8080
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.66.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: /response/headers/Content-Type text/xml
< Date: Thu, 24 Oct 2019 15:28:39 GMT
< Content-Length: 0
< 
* Connection #0 to host localhost left intact
```
Expected result:
`Content-Type: text/xml`

Obtained result:
`Content-Type: /response/headers/Content-Type text/xml`

**Comment by nilp0inter** [comment]
We should check that the same behavior is not happening with cookies, status codes and body. Good catch!

**Comment by panchoh** [comment]
Indeed, it does affect cookies, status codes and body as well.
The fix I'm working on takes care of all of them, though :-)
