### ISSUE TITLE
Realtime stream doesn't works

### ISSUE THREAD

**Issue by cr0hn** [BBVA/kapow#72]
When you launch a tool that write into the stdout, but doesn't write a lot to information, Kapow! doesn't send the console information until the tools finish their execution. 

Example:

nmap.pow:

```
kapow route add -X POST /nmap-stream - <<-'EOF'
    {
        nmap -Pn -T1 -n -p - -v $(kapow get /request/form/ip)
    } | kapow set /response/stream

EOF
```

Curl call:

```
$ curl -v http://localhost:9001/nmap-stream -d "ip=127.0.0.1"
```

Also tried forcing HTTP2 in curl:

```
$ curl --http2 -v http://localhost:9001/nmap-stream -d "ip=127.0.0.1"
```

Curl doesn't receive any data until nmap finish.

**Comment by nilp0inter** [comment]
This is intentional until we implement parametrised resources.

In the future for the behavior that you expect you must use something like this

```
kapow set /response/stream?buffer=off
```
