### ISSUE TITLE
Add usage examples for non-developers 

### ISSUE THREAD

**Issue by cr0hn** [BBVA/kapow#75]
Kapow! is a powerful tool but, as user, is very complicated to start using the projects because missing examples

**Comment by zoobab** [comment]
Felt in the same problem here while trying to use it.

Here are some recommantations:

1.  Move all those docs to simple Markdown
2. Start with a simple example like `echo helloworld`
3. Make a second one with a `echo helloworld | sed -e s/world/belgium/g `
4. Make a third one with a shell script like `kapow script.sh`

**Comment by nilp0inter** [comment]
Hi, @zoobab. Thank you for your feedback it is very appreciated.

Have you seen the rendered documentation at http://kapow.readthedocs.io? Please check it out and tell us what you think.

**Comment by nilp0inter** [comment]
These are the changes made to address this issue:

- [x] [A directory with examples](https://github.com/BBVA/kapow/tree/master/examples) at the root of the repo.  Examples start from the typical "Hello World!" and buildup to more advanced (and useful) topics.
- [x] [A warning in the "docs" folder](https://github.com/BBVA/kapow/blob/master/docs/README.md) to redirect users to [Read the Docs](http://kapow.readthedocs.io).
