### ISSUE TITLE
Kapow! server reject connections after launch long time service

### ISSUE THREAD

**Issue by cr0hn** [BBVA/kapow#8]
Using this .pow file:

`bash
kapow route add -X POST /tools/network/nmap -c 'nmap -v -Pn -n -sS -sS -A "$(request /form/ip)" | response /stream'
`

After launch Kapow! this above rules and launch 3 executions and cancel them (with a CTRL+C), the Kapow! service reject connections until one *nmap* execution finishes.

It appears that, when CTRL+C was break the connection with Kapow! serve, it doesn't stop the *nmap* background process. 

Screenshot of curl calling the service:

![photo_2019-08-05_13-00-15](https://user-images.githubusercontent.com/4076390/62460428-48694200-b782-11e9-9ba9-0b49601656dc.jpg)

Screenshot of the Kapow! console:

![photo_2019-08-05_13-00-37](https://user-images.githubusercontent.com/4076390/62460479-646ce380-b782-11e9-8f58-281e9304c0f1.jpg)

**Comment by nilp0inter** [comment]
I can't reproduce it with the latest Docker image. Maybe fix.
