### ISSUE TITLE
Use os-dependent interpreter for running the .pow file

### ISSUE THREAD

**Issue by panchoh** [BBVA/kapow#83]
`kapow server file.pow` uses `bash` (hardcoded) to run `file.pow`.

This hinders using `kapow` on Windows.

https://github.com/BBVA/kapow/blob/69cbcd7fdacf318f4f59ad58f4a852c2e7054038/internal/cmd/server.go#L55

Related to #48.

**Comment by hhurtado** [comment]
Closed, contiue in #95
